version: '3'
services:
  db:
    build: db
    environment:
      - DATADIR=/var/lib/mysql
      - MYSQL_ROOT_PASSWORD=gitbucket
      - MYSQL_DATABASE=gitbucket
      - MYSQL_USER=gitbucket
      - MYSQL_PASSWORD=gitbucket
      - TZ=Asia/Tokyo
    ports:
      - "50103:3306"
    restart: always
    volumes:
      - db-data:/var/lib/mysql
  app:
    build:
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
      context: app
    depends_on:
      - db
    environment:
      - GITBUCKET_DB_HOST=db
      - GITBUCKET_DB_NAME=gitbucket
      - GITBUCKET_DB_USER=gitbucket
      - GITBUCKET_DB_PASSWORD=gitbucket
      - JAVA_OPTS="-server"
      - GITBUCKET_OPTS="--port=80"
      - TZ=Asia/Tokyo
    ports:
      - "50003:80"
      - "29418:29418"
    restart: always
    volumes:
      - app-data:/gitbucket
volumes:
  db-data: {}
  app-data: {}
